apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: supinfo4kube/api-gateway:1.1.0

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  ports:
    - port: 8080
  selector:
    app: api-gateway