apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: supinfo4kube/web-app:1.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: web-app
